### ISSUE TITLE
sendStart not invoke

### ISSUE THREAD

**Issue by phoenixsky** [liuguangqiang/AsyncOkHttp#2]
RequestTask.class
public void execute() {
        try {
            mResponseHandler.sendStart(); // I write here
            Response response = mClient.newCall(mRequest).execute();
            int code = response.code();
            String responseString = "without response body";
            if (response.body() != null)
                responseString = response.body().string();

```
        if (response.isSuccessful())
            mResponseHandler.sendSuccess(code, responseString);
        else
            mResponseHandler.sendFailure(code, responseString);
    } catch (IOException e) {
        String error = "unknown";
        if (e.getMessage() != null) error = e.getMessage();

        if (error.equals("Canceled"))
            mResponseHandler.sendCancel();
        else
            mResponseHandler.sendFailure(0, error);
    }
}
```

**Comment by liuguangqiang** [comment]
Fixed , thanks!
